# Generated by Django 4.0.3 on 2022-08-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0003_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='sub_category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='students',
            name='department',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
