# Generated by Django 4.0.3 on 2022-09-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0005_alter_books_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.IntegerField(),
        ),
    ]
